"""add instrument_type and source_file to symboldetail

Revision ID: e693bbf70b73
Revises: 0eb24378ca90
Create Date: 2025-08-25 11:25:08.276656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e693bbf70b73'
down_revision: Union[str, Sequence[str], None] = '0eb24378ca90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symboldetail', sa.Column('instrument_type', sa.Text(), nullable=True))
    op.add_column('symboldetail', sa.Column('source_file', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symboldetail', 'source_file')
    op.drop_column('symboldetail', 'instrument_type')
    # ### end Alembic commands ###
